version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper-container
    networks:
      - development-network
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    container_name: kafka-container
    networks:
      - development-network
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - "zookeeper"
  database:
    image: postgres
    container_name: database-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin

networks:
  development-network:
    driver: bridge